package com.little.g.springcloud.user.mapper;

import com.little.g.springcloud.user.model.OAuthUser;
import com.little.g.springcloud.user.model.OAuthUserExample;
import com.little.g.springcloud.user.model.OAuthUserKey;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OAuthUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	long countByExample(OAuthUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	int deleteByExample(OAuthUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(OAuthUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	int insert(OAuthUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	int insertSelective(OAuthUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	OAuthUser selectOneByExample(OAuthUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	OAuthUser selectOneByExampleSelective(@Param("example") OAuthUserExample example,
			@Param("selective") OAuthUser.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	List<OAuthUser> selectByExampleSelective(@Param("example") OAuthUserExample example,
			@Param("selective") OAuthUser.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	List<OAuthUser> selectByExample(OAuthUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	OAuthUser selectByPrimaryKeySelective(@Param("record") OAuthUserKey key,
			@Param("selective") OAuthUser.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	OAuthUser selectByPrimaryKey(OAuthUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") OAuthUser record,
			@Param("example") OAuthUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") OAuthUser record,
			@Param("example") OAuthUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(OAuthUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table oauth_user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(OAuthUser record);

}
