package com.little.g.springcloud.user.mapper;

import com.little.g.springcloud.user.model.UserDeviceToken;
import com.little.g.springcloud.user.model.UserDeviceTokenExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserDeviceTokenMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	long countByExample(UserDeviceTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	int deleteByExample(UserDeviceTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	int insert(UserDeviceToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	int insertSelective(UserDeviceToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	UserDeviceToken selectOneByExample(UserDeviceTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	UserDeviceToken selectOneByExampleSelective(
			@Param("example") UserDeviceTokenExample example,
			@Param("selective") UserDeviceToken.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	List<UserDeviceToken> selectByExampleSelective(
			@Param("example") UserDeviceTokenExample example,
			@Param("selective") UserDeviceToken.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	List<UserDeviceToken> selectByExample(UserDeviceTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	UserDeviceToken selectByPrimaryKeySelective(@Param("id") Long id,
			@Param("selective") UserDeviceToken.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	UserDeviceToken selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") UserDeviceToken record,
			@Param("example") UserDeviceTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") UserDeviceToken record,
			@Param("example") UserDeviceTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(UserDeviceToken record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_device_token
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(UserDeviceToken record);

}
