package com.little.g.springcloud.thirdpay.model;

import java.util.ArrayList;
import java.util.Arrays;

public class PayChannel {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.code
	 *
	 * @mbg.generated
	 */
	private String code;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.config_version
	 *
	 * @mbg.generated
	 */
	private String configVersion;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.max_pay_fee
	 *
	 * @mbg.generated
	 */
	private Long maxPayFee;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.min_pay_fee
	 *
	 * @mbg.generated
	 */
	private Long minPayFee;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.status
	 *
	 * @mbg.generated
	 */
	private Byte status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.memo
	 *
	 * @mbg.generated
	 */
	private String memo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column pay_channel.thumbnail
	 *
	 * @mbg.generated
	 */
	private String thumbnail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.id
	 * @return the value of pay_channel.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.id
	 * @param id the value for pay_channel.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.name
	 * @return the value of pay_channel.name
	 *
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.name
	 * @param name the value for pay_channel.name
	 *
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.code
	 * @return the value of pay_channel.code
	 *
	 * @mbg.generated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.code
	 * @param code the value for pay_channel.code
	 *
	 * @mbg.generated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.config_version
	 * @return the value of pay_channel.config_version
	 *
	 * @mbg.generated
	 */
	public String getConfigVersion() {
		return configVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.config_version
	 * @param configVersion the value for pay_channel.config_version
	 *
	 * @mbg.generated
	 */
	public void setConfigVersion(String configVersion) {
		this.configVersion = configVersion == null ? null : configVersion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.max_pay_fee
	 * @return the value of pay_channel.max_pay_fee
	 *
	 * @mbg.generated
	 */
	public Long getMaxPayFee() {
		return maxPayFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.max_pay_fee
	 * @param maxPayFee the value for pay_channel.max_pay_fee
	 *
	 * @mbg.generated
	 */
	public void setMaxPayFee(Long maxPayFee) {
		this.maxPayFee = maxPayFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.min_pay_fee
	 * @return the value of pay_channel.min_pay_fee
	 *
	 * @mbg.generated
	 */
	public Long getMinPayFee() {
		return minPayFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.min_pay_fee
	 * @param minPayFee the value for pay_channel.min_pay_fee
	 *
	 * @mbg.generated
	 */
	public void setMinPayFee(Long minPayFee) {
		this.minPayFee = minPayFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.status
	 * @return the value of pay_channel.status
	 *
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.status
	 * @param status the value for pay_channel.status
	 *
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.memo
	 * @return the value of pay_channel.memo
	 *
	 * @mbg.generated
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.memo
	 * @param memo the value for pay_channel.memo
	 *
	 * @mbg.generated
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column pay_channel.thumbnail
	 * @return the value of pay_channel.thumbnail
	 *
	 * @mbg.generated
	 */
	public String getThumbnail() {
		return thumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column pay_channel.thumbnail
	 * @param thumbnail the value for pay_channel.thumbnail
	 *
	 * @mbg.generated
	 */
	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail == null ? null : thumbnail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", code=").append(code);
		sb.append(", configVersion=").append(configVersion);
		sb.append(", maxPayFee=").append(maxPayFee);
		sb.append(", minPayFee=").append(minPayFee);
		sb.append(", status=").append(status);
		sb.append(", memo=").append(memo);
		sb.append(", thumbnail=").append(thumbnail);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		PayChannel other = (PayChannel) that;
		return (this.getId() == null ? other.getId() == null
				: this.getId().equals(other.getId()))
				&& (this.getName() == null ? other.getName() == null
						: this.getName().equals(other.getName()))
				&& (this.getCode() == null ? other.getCode() == null
						: this.getCode().equals(other.getCode()))
				&& (this.getConfigVersion() == null ? other.getConfigVersion() == null
						: this.getConfigVersion().equals(other.getConfigVersion()))
				&& (this.getMaxPayFee() == null ? other.getMaxPayFee() == null
						: this.getMaxPayFee().equals(other.getMaxPayFee()))
				&& (this.getMinPayFee() == null ? other.getMinPayFee() == null
						: this.getMinPayFee().equals(other.getMinPayFee()))
				&& (this.getStatus() == null ? other.getStatus() == null
						: this.getStatus().equals(other.getStatus()))
				&& (this.getMemo() == null ? other.getMemo() == null
						: this.getMemo().equals(other.getMemo()))
				&& (this.getThumbnail() == null ? other.getThumbnail() == null
						: this.getThumbnail().equals(other.getThumbnail()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
		result = prime * result
				+ ((getConfigVersion() == null) ? 0 : getConfigVersion().hashCode());
		result = prime * result
				+ ((getMaxPayFee() == null) ? 0 : getMaxPayFee().hashCode());
		result = prime * result
				+ ((getMinPayFee() == null) ? 0 : getMinPayFee().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
		result = prime * result
				+ ((getThumbnail() == null) ? 0 : getThumbnail().hashCode());
		return result;
	}

	/**
	 * This enum was generated by MyBatis Generator. This enum corresponds to the database
	 * table pay_channel
	 *
	 * @mbg.generated
	 */
	public enum Column {

		id("id", "id", "INTEGER", false), name("name", "name", "VARCHAR", true), code(
				"code", "code", "VARCHAR", false), configVersion("config_version",
						"configVersion", "VARCHAR", false), maxPayFee("max_pay_fee",
								"maxPayFee", "BIGINT", false), minPayFee("min_pay_fee",
										"minPayFee", "BIGINT", false), status("status",
												"status", "TINYINT", true), memo("memo",
														"memo", "VARCHAR",
														false), thumbnail("thumbnail",
																"thumbnail", "VARCHAR",
																false);

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		private static final String BEGINNING_DELIMITER = "`";

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		private static final String ENDING_DELIMITER = "`";

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		private final String column;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		private final boolean isColumnNameDelimited;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		private final String javaProperty;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		private final String jdbcType;

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public String value() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public String getValue() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public String getJavaProperty() {
			return this.javaProperty;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public String getJdbcType() {
			return this.jdbcType;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		Column(String column, String javaProperty, String jdbcType,
				boolean isColumnNameDelimited) {
			this.column = column;
			this.javaProperty = javaProperty;
			this.jdbcType = jdbcType;
			this.isColumnNameDelimited = isColumnNameDelimited;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public String desc() {
			return this.getEscapedColumnName() + " DESC";
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public String asc() {
			return this.getEscapedColumnName() + " ASC";
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public static Column[] excludes(Column... excludes) {
			ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
			if (excludes != null && excludes.length > 0) {
				columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
			}
			return columns.toArray(new Column[] {});
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public static Column[] all() {
			return Column.values();
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public String getEscapedColumnName() {
			if (this.isColumnNameDelimited) {
				return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column)
						.append(ENDING_DELIMITER).toString();
			}
			else {
				return this.column;
			}
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table pay_channel
		 *
		 * @mbg.generated
		 */
		public String getAliasedEscapedColumnName() {
			return this.getEscapedColumnName();
		}

	}

}