dubbo:
  scan:
    base-packages: com.little.g.springcloud.sample.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 9091
      server: netty
  registry:
#   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost
#   The traditional Dubbo's registry
#   address: zookeeper://127.0.0.1:2181
  cloud:
    # The subscribed services in consumer side
    subscribed-services:
feign:
  hystrix:
    enabled: true