package com.little.g.springcloud.common.enums;

public enum Deleted {

    NOT_DELETED(new Boolean("0"), "未删除"), IS_DELETED(new Boolean("1"), "已删除");

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table litemall_ad
     *
     * @mbg.generated
     */
    private final Boolean value;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table litemall_ad
     *
     * @mbg.generated
     */
    private final String name;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table litemall_ad
     *
     * @mbg.generated
     */
    Deleted(Boolean value, String name) {
        this.value = value;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table litemall_ad
     *
     * @mbg.generated
     */
    public Boolean getValue() {
        return this.value;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table litemall_ad
     *
     * @mbg.generated
     */
    public Boolean value() {
        return this.value;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table litemall_ad
     *
     * @mbg.generated
     */
    public String getName() {
        return this.name;
    }

}
