package com.little.g.springcloud.pay.mapper;

import com.little.g.springcloud.pay.model.BalanceCheckpoint;
import com.little.g.springcloud.pay.model.BalanceCheckpointExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BalanceCheckpointMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    long countByExample(BalanceCheckpointExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    int deleteByExample(BalanceCheckpointExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    int insert(BalanceCheckpoint record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    int insertSelective(BalanceCheckpoint record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    BalanceCheckpoint selectOneByExample(BalanceCheckpointExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    BalanceCheckpoint selectOneByExampleSelective(
            @Param("example") BalanceCheckpointExample example,
            @Param("selective") BalanceCheckpoint.Column... selective);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    List<BalanceCheckpoint> selectByExampleSelective(
            @Param("example") BalanceCheckpointExample example,
            @Param("selective") BalanceCheckpoint.Column... selective);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    List<BalanceCheckpoint> selectByExample(BalanceCheckpointExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    BalanceCheckpoint selectByPrimaryKeySelective(@Param("id") Long id,
                                                  @Param("selective") BalanceCheckpoint.Column... selective);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    BalanceCheckpoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BalanceCheckpoint record,
                                 @Param("example") BalanceCheckpointExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BalanceCheckpoint record,
                        @Param("example") BalanceCheckpointExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BalanceCheckpoint record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BalanceCheckpoint record);

}
