package com.little.g.springcloud.pay.mapper;

import com.little.g.springcloud.pay.model.Preorder;
import com.little.g.springcloud.pay.model.PreorderExample;
import com.little.g.springcloud.pay.model.PreorderKey;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PreorderMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    long countByExample(PreorderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    int deleteByExample(PreorderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(PreorderKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    int insert(Preorder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    int insertSelective(Preorder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    Preorder selectOneByExample(PreorderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    Preorder selectOneByExampleSelective(@Param("example") PreorderExample example,
                                         @Param("selective") Preorder.Column... selective);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    List<Preorder> selectByExampleSelective(@Param("example") PreorderExample example,
                                            @Param("selective") Preorder.Column... selective);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    List<Preorder> selectByExample(PreorderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    Preorder selectByPrimaryKeySelective(@Param("record") PreorderKey key,
                                         @Param("selective") Preorder.Column... selective);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    Preorder selectByPrimaryKey(PreorderKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Preorder record,
                                 @Param("example") PreorderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Preorder record,
                        @Param("example") PreorderExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Preorder record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table preorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Preorder record);

}
