package com.little.g.springcloud.pay.mapper;

import com.little.g.springcloud.pay.model.UserAccount;
import com.little.g.springcloud.pay.model.UserAccountExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	long countByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	int deleteByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	int insert(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	int insertSelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	UserAccount selectOneByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	UserAccount selectOneByExampleSelective(@Param("example") UserAccountExample example,
			@Param("selective") UserAccount.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	List<UserAccount> selectByExampleSelective(
			@Param("example") UserAccountExample example,
			@Param("selective") UserAccount.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	List<UserAccount> selectByExample(UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	UserAccount selectByPrimaryKeySelective(@Param("uid") Integer uid,
			@Param("selective") UserAccount.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	UserAccount selectByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") UserAccount record,
			@Param("example") UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") UserAccount record,
			@Param("example") UserAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(UserAccount record);

}
