package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.time.LocalDateTime;

@ApiModel("团购活动")
public class LitemallGrouponDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_groupon
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_groupon
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("id")
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.order_id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("关联的订单ID")
	private Integer orderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.groupon_id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("如果是开团用户，则groupon_id是0；如果是参团用户，则groupon_id是团购活动ID")
	private Integer grouponId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.rules_id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("团购规则ID，关联litemall_groupon_rules表ID字段")
	private Integer rulesId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.user_id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("用户ID")
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.share_url
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("团购分享图片地址")
	private String shareUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.creator_user_id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("开团用户ID")
	private Integer creatorUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.creator_user_time
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("开团时间")
	private LocalDateTime creatorUserTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.status
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("团购活动状态，开团未支付则0，开团中则1，开团失败则2")
	private Short status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.add_time
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("创建时间")
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.update_time
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("更新时间")
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon.deleted
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("是否删除")
	private Boolean deleted;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getGrouponId() {
		return grouponId;
	}

	public void setGrouponId(Integer grouponId) {
		this.grouponId = grouponId;
	}

	public Integer getRulesId() {
		return rulesId;
	}

	public void setRulesId(Integer rulesId) {
		this.rulesId = rulesId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getShareUrl() {
		return shareUrl;
	}

	public void setShareUrl(String shareUrl) {
		this.shareUrl = shareUrl;
	}

	public Integer getCreatorUserId() {
		return creatorUserId;
	}

	public void setCreatorUserId(Integer creatorUserId) {
		this.creatorUserId = creatorUserId;
	}

	public LocalDateTime getCreatorUserTime() {
		return creatorUserTime;
	}

	public void setCreatorUserTime(LocalDateTime creatorUserTime) {
		this.creatorUserTime = creatorUserTime;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
