package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;

import java.io.Serializable;
import java.time.LocalDateTime;

public class LitemallFeedbackDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_feedback
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_feedback
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.user_id
	 *
	 * @mbg.generated
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.username
	 *
	 * @mbg.generated
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.mobile
	 *
	 * @mbg.generated
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.feed_type
	 *
	 * @mbg.generated
	 */
	private String feedType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.content
	 *
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.status
	 *
	 * @mbg.generated
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.has_picture
	 *
	 * @mbg.generated
	 */
	private Boolean hasPicture;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.pic_urls
	 *
	 * @mbg.generated
	 */
	private String[] picUrls;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.add_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.update_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_feedback.deleted
	 *
	 * @mbg.generated
	 */
	private Boolean deleted;

	public static Boolean getIsDeleted() {
		return IS_DELETED;
	}

	public static Boolean getNotDeleted() {
		return NOT_DELETED;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getFeedType() {
		return feedType;
	}

	public void setFeedType(String feedType) {
		this.feedType = feedType;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Boolean getHasPicture() {
		return hasPicture;
	}

	public void setHasPicture(Boolean hasPicture) {
		this.hasPicture = hasPicture;
	}

	public String[] getPicUrls() {
		return picUrls;
	}

	public void setPicUrls(String[] picUrls) {
		this.picUrls = picUrls;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
