package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.time.LocalDateTime;

@ApiModel("足迹")
public class LitemallFootprintDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_footprint
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_footprint
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_footprint.id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("足迹ID")
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_footprint.user_id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("用户ID")
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_footprint.goods_id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("商品ID")
	private Integer goodsId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_footprint.add_time
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("添加时间")
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_footprint.update_time
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("更新时间")
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_footprint.deleted
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("是否已删除")
	private Boolean deleted;

	public static Boolean getIsDeleted() {
		return IS_DELETED;
	}

	public static Boolean getNotDeleted() {
		return NOT_DELETED;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
