package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;

import java.io.Serializable;
import java.time.LocalDateTime;

public class LitemallLogDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_log
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_log
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.admin
	 *
	 * @mbg.generated
	 */
	private String admin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.ip
	 *
	 * @mbg.generated
	 */
	private String ip;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.type
	 *
	 * @mbg.generated
	 */
	private Integer type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.action
	 *
	 * @mbg.generated
	 */
	private String action;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.status
	 *
	 * @mbg.generated
	 */
	private Boolean status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.result
	 *
	 * @mbg.generated
	 */
	private String result;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.comment
	 *
	 * @mbg.generated
	 */
	private String comment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.add_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.update_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_log.deleted
	 *
	 * @mbg.generated
	 */
	private Boolean deleted;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAdmin() {
		return admin;
	}

	public void setAdmin(String admin) {
        this.admin = admin;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
        this.ip = ip;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
        this.action = action;
	}

	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
        this.result = result;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
        this.comment = comment;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
