package com.little.g.springcloud.mall.dto;

import java.io.Serializable;

public class LitemallRegionDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_region.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_region.pid
	 *
	 * @mbg.generated
	 */
	private Integer pid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_region.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_region.type
	 *
	 * @mbg.generated
	 */
	private Byte type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_region.code
	 *
	 * @mbg.generated
	 */
	private Integer code;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
        this.name = name;
	}

	public Byte getType() {
		return type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public Integer getCode() {
		return code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

}
