package com.little.g.springcloud.mall.dto;

import java.io.Serializable;
import java.time.LocalDateTime;

public class LitemallAddressDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.user_id
	 *
	 * @mbg.generated
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.province
	 *
	 * @mbg.generated
	 */
	private String province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.city
	 *
	 * @mbg.generated
	 */
	private String city;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.county
	 *
	 * @mbg.generated
	 */
	private String county;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.address_detail
	 *
	 * @mbg.generated
	 */
	private String addressDetail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.area_code
	 *
	 * @mbg.generated
	 */
	private String areaCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.postal_code
	 *
	 * @mbg.generated
	 */
	private String postalCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.tel
	 *
	 * @mbg.generated
	 */
	private String tel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.is_default
	 *
	 * @mbg.generated
	 */
	private Boolean isDefault;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.add_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.update_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_address.deleted
	 *
	 * @mbg.generated
	 */
	private Boolean deleted;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getAddressDetail() {
		return addressDetail;
	}

	public void setAddressDetail(String addressDetail) {
		this.addressDetail = addressDetail;
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Boolean getDefault() {
		return isDefault;
	}

	public void setDefault(Boolean aDefault) {
		isDefault = aDefault;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
