package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@ApiModel("售后服务")
public class LitemallAftersaleDTO implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table litemall_aftersale
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table litemall_aftersale
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.id
     *
     * @mbg.generated
     */
    @ApiModelProperty("售后ID")
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.aftersale_sn
     *
     * @mbg.generated
     */
    @ApiModelProperty("售后sn")
    private String aftersaleSn;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.order_id
     *
     * @mbg.generated
     */
    @ApiModelProperty("订单号")
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.type
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "类型 0是未收货退款，1是已收货（无需退货）退款，2用户退货退款",
            allowableValues = "0,1,2")
    private Short type;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.reason
     *
     * @mbg.generated
     */
    @ApiModelProperty("原因")
    private String reason;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.amount
     *
     * @mbg.generated
     */
    @ApiModelProperty("金额")
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.pictures
     *
     * @mbg.generated
     */
    @ApiModelProperty("图片列表")
    private String[] pictures;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.comment
     *
     * @mbg.generated
     */
    @ApiModelProperty("描述")
    private String comment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.status
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "售后状态  0是可申请，1是用户已申请，2是管理员审核通过，3是管理员退款成功，4是管理员审核拒绝，5是用户已取消",
            allowableValues = "0,1,2,3,4,5")
    private Short status;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.handle_time
     *
     * @mbg.generated
     */
    @ApiModelProperty("处理时间")
    private LocalDateTime handleTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.add_time
     *
     * @mbg.generated
     */
    @ApiModelProperty("添加时间")
    private LocalDateTime addTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.update_time
     *
     * @mbg.generated
     */
    @ApiModelProperty("更新时间")
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column litemall_aftersale.deleted
     *
     * @mbg.generated
     */
    @ApiModelProperty("是否删除")
    private Boolean deleted;

    public static Boolean getIsDeleted() {
        return IS_DELETED;
    }

    public static Boolean getNotDeleted() {
        return NOT_DELETED;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAftersaleSn() {
        return aftersaleSn;
    }

    public void setAftersaleSn(String aftersaleSn) {
        this.aftersaleSn = aftersaleSn;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Short getType() {
        return type;
    }

    public void setType(Short type) {
        this.type = type;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String[] getPictures() {
        return pictures;
    }

    public void setPictures(String[] pictures) {
        this.pictures = pictures;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public LocalDateTime getHandleTime() {
        return handleTime;
    }

    public void setHandleTime(LocalDateTime handleTime) {
        this.handleTime = handleTime;
    }

    public LocalDateTime getAddTime() {
        return addTime;
    }

    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

}
