package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class LitemallUserDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_user
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_user
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.username
	 *
	 * @mbg.generated
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.password
	 *
	 * @mbg.generated
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.gender
	 *
	 * @mbg.generated
	 */
	private Byte gender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.birthday
	 *
	 * @mbg.generated
	 */
	private LocalDate birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.last_login_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime lastLoginTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.last_login_ip
	 *
	 * @mbg.generated
	 */
	private String lastLoginIp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.user_level
	 *
	 * @mbg.generated
	 */
	private Byte userLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.nickname
	 *
	 * @mbg.generated
	 */
	private String nickname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.mobile
	 *
	 * @mbg.generated
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.avatar
	 *
	 * @mbg.generated
	 */
	private String avatar;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.weixin_openid
	 *
	 * @mbg.generated
	 */
	private String weixinOpenid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.session_key
	 *
	 * @mbg.generated
	 */
	private String sessionKey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.status
	 *
	 * @mbg.generated
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.add_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.update_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_user.deleted
	 *
	 * @mbg.generated
	 */
	private Boolean deleted;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
        this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
        this.password = password;
	}

	public Byte getGender() {
		return gender;
	}

	public void setGender(Byte gender) {
		this.gender = gender;
	}

	public LocalDate getBirthday() {
		return birthday;
	}

	public void setBirthday(LocalDate birthday) {
		this.birthday = birthday;
	}

	public LocalDateTime getLastLoginTime() {
		return lastLoginTime;
	}

	public void setLastLoginTime(LocalDateTime lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public String getLastLoginIp() {
		return lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
	}

	public Byte getUserLevel() {
		return userLevel;
	}

	public void setUserLevel(Byte userLevel) {
		this.userLevel = userLevel;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
        this.nickname = nickname;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
        this.mobile = mobile;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
        this.avatar = avatar;
	}

	public String getWeixinOpenid() {
		return weixinOpenid;
	}

	public void setWeixinOpenid(String weixinOpenid) {
        this.weixinOpenid = weixinOpenid;
	}

	public String getSessionKey() {
		return sessionKey;
	}

	public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
	}

	public Byte getStatus() {
		return status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
