package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@ApiModel("团购规则")
public class LitemallGrouponRulesDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_groupon_rules
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_groupon_rules
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("团购规则ID")
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.goods_id
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("商品ID")
	private Integer goodsId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.goods_name
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("商品名称")
	private String goodsName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.pic_url
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("商品图片或者商品货品图片")
	private String picUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.discount
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("优惠金额")
	private BigDecimal discount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.discount_member
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("达到优惠条件的人数")
	private Integer discountMember;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.expire_time
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("过期时间")
	private LocalDateTime expireTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.status
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("团购规则状态")
	private Short status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.add_time
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("添加状态")
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.update_time
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("更新状态")
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_groupon_rules.deleted
	 *
	 * @mbg.generated
	 */
	@ApiModelProperty("删除状态")
	private Boolean deleted;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getGoodsId() {
		return goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public String getGoodsName() {
		return goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getPicUrl() {
		return picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public BigDecimal getDiscount() {
		return discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public Integer getDiscountMember() {
		return discountMember;
	}

	public void setDiscountMember(Integer discountMember) {
		this.discountMember = discountMember;
	}

	public LocalDateTime getExpireTime() {
		return expireTime;
	}

	public void setExpireTime(LocalDateTime expireTime) {
		this.expireTime = expireTime;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
