package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class LitemallAftersaleDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_aftersale
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_aftersale
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.aftersale_sn
	 *
	 * @mbg.generated
	 */
	private String aftersaleSn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.order_id
	 *
	 * @mbg.generated
	 */
	private Integer orderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.user_id
	 *
	 * @mbg.generated
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.type
	 *
	 * @mbg.generated
	 */
	private Short type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.reason
	 *
	 * @mbg.generated
	 */
	private String reason;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.amount
	 *
	 * @mbg.generated
	 */
	private BigDecimal amount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.pictures
	 *
	 * @mbg.generated
	 */
	private String[] pictures;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.comment
	 *
	 * @mbg.generated
	 */
	private String comment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.status
	 *
	 * @mbg.generated
	 */
	private Short status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.handle_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime handleTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.add_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.update_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_aftersale.deleted
	 *
	 * @mbg.generated
	 */
	private Boolean deleted;

	public static Boolean getIsDeleted() {
		return IS_DELETED;
	}

	public static Boolean getNotDeleted() {
		return NOT_DELETED;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAftersaleSn() {
		return aftersaleSn;
	}

	public void setAftersaleSn(String aftersaleSn) {
		this.aftersaleSn = aftersaleSn;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Short getType() {
		return type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String[] getPictures() {
		return pictures;
	}

	public void setPictures(String[] pictures) {
		this.pictures = pictures;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public LocalDateTime getHandleTime() {
		return handleTime;
	}

	public void setHandleTime(LocalDateTime handleTime) {
		this.handleTime = handleTime;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
