package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;

import java.io.Serializable;
import java.time.LocalDateTime;

public class LitemallCommentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_comment
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_comment
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.value_id
	 *
	 * @mbg.generated
	 */
	private Integer valueId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.type
	 *
	 * @mbg.generated
	 */
	private Byte type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.content
	 *
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.admin_content
	 *
	 * @mbg.generated
	 */
	private String adminContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.user_id
	 *
	 * @mbg.generated
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.has_picture
	 *
	 * @mbg.generated
	 */
	private Boolean hasPicture;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.pic_urls
	 *
	 * @mbg.generated
	 */
	private String[] picUrls;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.star
	 *
	 * @mbg.generated
	 */
	private Short star;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.add_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.update_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_comment.deleted
	 *
	 * @mbg.generated
	 */
	private Boolean deleted;

	public static Boolean getIsDeleted() {
		return IS_DELETED;
	}

	public static Boolean getNotDeleted() {
		return NOT_DELETED;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getValueId() {
		return valueId;
	}

	public void setValueId(Integer valueId) {
		this.valueId = valueId;
	}

	public Byte getType() {
		return type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAdminContent() {
		return adminContent;
	}

	public void setAdminContent(String adminContent) {
		this.adminContent = adminContent;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Boolean getHasPicture() {
		return hasPicture;
	}

	public void setHasPicture(Boolean hasPicture) {
		this.hasPicture = hasPicture;
	}

	public String[] getPicUrls() {
		return picUrls;
	}

	public void setPicUrls(String[] picUrls) {
		this.picUrls = picUrls;
	}

	public Short getStar() {
		return star;
	}

	public void setStar(Short star) {
		this.star = star;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
