package com.little.g.springcloud.mall.dto;

import com.little.g.springcloud.common.enums.Deleted;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class LitemallOrderDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_order
	 *
	 * @mbg.generated
	 */
	public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table litemall_order
	 *
	 * @mbg.generated
	 */
	public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.user_id
	 *
	 * @mbg.generated
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.order_sn
	 *
	 * @mbg.generated
	 */
	private String orderSn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.order_status
	 *
	 * @mbg.generated
	 */
	private Short orderStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.aftersale_status
	 *
	 * @mbg.generated
	 */
	private Short aftersaleStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.consignee
	 *
	 * @mbg.generated
	 */
	private String consignee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.mobile
	 *
	 * @mbg.generated
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.address
	 *
	 * @mbg.generated
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.message
	 *
	 * @mbg.generated
	 */
	private String message;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.goods_price
	 *
	 * @mbg.generated
	 */
	private BigDecimal goodsPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.freight_price
	 *
	 * @mbg.generated
	 */
	private BigDecimal freightPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.coupon_price
	 *
	 * @mbg.generated
	 */
	private BigDecimal couponPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.integral_price
	 *
	 * @mbg.generated
	 */
	private BigDecimal integralPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.groupon_price
	 *
	 * @mbg.generated
	 */
	private BigDecimal grouponPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.order_price
	 *
	 * @mbg.generated
	 */
	private BigDecimal orderPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.actual_price
	 *
	 * @mbg.generated
	 */
	private BigDecimal actualPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.pay_id
	 *
	 * @mbg.generated
	 */
	private String payId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.pay_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime payTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.ship_sn
	 *
	 * @mbg.generated
	 */
	private String shipSn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.ship_channel
	 *
	 * @mbg.generated
	 */
	private String shipChannel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.ship_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime shipTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.refund_amount
	 *
	 * @mbg.generated
	 */
	private BigDecimal refundAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.refund_type
	 *
	 * @mbg.generated
	 */
	private String refundType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.refund_content
	 *
	 * @mbg.generated
	 */
	private String refundContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.refund_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime refundTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.confirm_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime confirmTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.comments
	 *
	 * @mbg.generated
	 */
	private Short comments;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.end_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime endTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.add_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.update_time
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column litemall_order.deleted
	 *
	 * @mbg.generated
	 */
	private Boolean deleted;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getOrderSn() {
		return orderSn;
	}

	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn;
	}

	public Short getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(Short orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Short getAftersaleStatus() {
		return aftersaleStatus;
	}

	public void setAftersaleStatus(Short aftersaleStatus) {
		this.aftersaleStatus = aftersaleStatus;
	}

	public String getConsignee() {
		return consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public BigDecimal getGoodsPrice() {
		return goodsPrice;
	}

	public void setGoodsPrice(BigDecimal goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	public BigDecimal getFreightPrice() {
		return freightPrice;
	}

	public void setFreightPrice(BigDecimal freightPrice) {
		this.freightPrice = freightPrice;
	}

	public BigDecimal getCouponPrice() {
		return couponPrice;
	}

	public void setCouponPrice(BigDecimal couponPrice) {
		this.couponPrice = couponPrice;
	}

	public BigDecimal getIntegralPrice() {
		return integralPrice;
	}

	public void setIntegralPrice(BigDecimal integralPrice) {
		this.integralPrice = integralPrice;
	}

	public BigDecimal getGrouponPrice() {
		return grouponPrice;
	}

	public void setGrouponPrice(BigDecimal grouponPrice) {
		this.grouponPrice = grouponPrice;
	}

	public BigDecimal getOrderPrice() {
		return orderPrice;
	}

	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	public BigDecimal getActualPrice() {
		return actualPrice;
	}

	public void setActualPrice(BigDecimal actualPrice) {
		this.actualPrice = actualPrice;
	}

	public String getPayId() {
		return payId;
	}

	public void setPayId(String payId) {
		this.payId = payId;
	}

	public LocalDateTime getPayTime() {
		return payTime;
	}

	public void setPayTime(LocalDateTime payTime) {
		this.payTime = payTime;
	}

	public String getShipSn() {
		return shipSn;
	}

	public void setShipSn(String shipSn) {
		this.shipSn = shipSn;
	}

	public String getShipChannel() {
		return shipChannel;
	}

	public void setShipChannel(String shipChannel) {
		this.shipChannel = shipChannel;
	}

	public LocalDateTime getShipTime() {
		return shipTime;
	}

	public void setShipTime(LocalDateTime shipTime) {
		this.shipTime = shipTime;
	}

	public BigDecimal getRefundAmount() {
		return refundAmount;
	}

	public void setRefundAmount(BigDecimal refundAmount) {
		this.refundAmount = refundAmount;
	}

	public String getRefundType() {
		return refundType;
	}

	public void setRefundType(String refundType) {
		this.refundType = refundType;
	}

	public String getRefundContent() {
		return refundContent;
	}

	public void setRefundContent(String refundContent) {
		this.refundContent = refundContent;
	}

	public LocalDateTime getRefundTime() {
		return refundTime;
	}

	public void setRefundTime(LocalDateTime refundTime) {
		this.refundTime = refundTime;
	}

	public LocalDateTime getConfirmTime() {
		return confirmTime;
	}

	public void setConfirmTime(LocalDateTime confirmTime) {
		this.confirmTime = confirmTime;
	}

	public Short getComments() {
		return comments;
	}

	public void setComments(Short comments) {
		this.comments = comments;
	}

	public LocalDateTime getEndTime() {
		return endTime;
	}

	public void setEndTime(LocalDateTime endTime) {
		this.endTime = endTime;
	}

	public LocalDateTime getAddTime() {
		return addTime;
	}

	public void setAddTime(LocalDateTime addTime) {
		this.addTime = addTime;
	}

	public LocalDateTime getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(LocalDateTime updateTime) {
		this.updateTime = updateTime;
	}

	public Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

}
