version: '3'

volumes:
  ovpn-data:
    driver: local

services:
  openvpn-server:
    image: "kylemanna/openvpn"
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ovpn-data:/etc/openvpn
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/opt/sql
      - ./mysql/init-sql:/docker-entrypoint-initdb.d

    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: little.g
    restart: always

  apollo:
    image: nobodyiam/apollo-quick-start
    container_name: apollo
    depends_on:
      - mysql
    ports:
      - "18080:8080"
      - "18070:8070"
    links:
      - "mysql:apollo-db"
    volumes:
      - ./apollo/demo.sh:/apollo-quick-start/demo.sh

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    env_file:
      - ./nacos/env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    depends_on:
      - mysql
    restart: on-failure
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
  openresty:
    restart: always
    image: openresty/openresty:alpine
    container_name: openresty
    ports:
      - '80'
      - '443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    #      - ./nginx/www:/var/www
    depends_on:
      - user-http
  user-server:
    image: user-server:${app_version}
    restart: always
    ports:
      - '20880'
    container_name: user-server
    depends_on:
      - mysql
      - redis
      - nacos
    environment:
      - NACOS_HOST=nacos
      - NACOS_PORT=8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=password
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=little.g
  pay-server:
    image: pay-server:${app_version}
    restart: always
    ports:
      - '20880'
    container_name: pay-server
    depends_on:
      - mysql
      - redis
      - nacos
      - user-server
    environment:
      - NACOS_HOST=nacos
      - NACOS_PORT=8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=password
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=little.g
  #  admin-server:
  #    image: admin-server:${app_version}
  #    restart: always
  #    ports:
  #      - '20880'
  #    container_name: admin-server
  #    depends_on:
  #      - mysql
  #      - redis
  #      - nacos
  #    environment:
  #      - NACOS_HOST=nacos
  #      - NACOS_PORT=8848
  #      - REDIS_HOST=redis
  #      - REDIS_PORT=6379
  #      - REDIS_PASS=password
  #      - MYSQL_HOST=mysql
  #      - MYSQL_PORT=3306
  #      - MYSQL_USER=root
  #      - MYSQL_PASS=little.g
  user-http:
    image: user-http:${app_version}
    restart: always
    ports:
      - '8080'
    container_name: user-http
    depends_on:
      - nacos
      - redis
      - user-server
    environment:
      - NACOS_HOST=nacos
      - NACOS_PORT=8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=password
#  pay-http:
#    image: pay-http:${app_version}
#    restart: always
#    ports:
#      - '8080'
#    container_name: pay-http
#    depends_on:
#      - nacos
#      - redis
#      - user-server
#      - pay-server
#    environment:
#      - NACOS_HOST=nacos
#      - NACOS_PORT=8848
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#      - REDIS_PASS=password
#  admin-http:
#    image: admin-http:${app_version}
#    restart: always
#    ports:
#      - '8080'
#    container_name: admin-http
#    depends_on:
#      - nacos
#      - redis
#      - admin-server
#    environment:
#      - NACOS_HOST=nacos
#      - NACOS_PORT=8848
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#      - REDIS_PASS=password






