package com.little.g.springcloud.pay.model;

import java.util.ArrayList;
import java.util.Arrays;

public class BalanceCheckpoint {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column balance_checkpoint.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column balance_checkpoint.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column balance_checkpoint.account_id
     *
     * @mbg.generated
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column balance_checkpoint.balance
     *
     * @mbg.generated
     */
    private Long balance;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column balance_checkpoint.frozen
     *
     * @mbg.generated
     */
    private Long frozen;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column balance_checkpoint.max_id
     *
     * @mbg.generated
     */
    private Long maxId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column balance_checkpoint.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of
     * the database column balance_checkpoint.id
     * @return the value of balance_checkpoint.id
     *
     * @mbg.generated
	 */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the
     * database column balance_checkpoint.id
     * @param id the value for balance_checkpoint.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of
     * the database column balance_checkpoint.uid
     *
     * @return the value of balance_checkpoint.uid
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the
     * database column balance_checkpoint.uid
     * @param uid the value for balance_checkpoint.uid
     *
     * @mbg.generated
	 */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of
     * the database column balance_checkpoint.account_id
     * @return the value of balance_checkpoint.account_id
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the
     * database column balance_checkpoint.account_id
     * @param accountId the value for balance_checkpoint.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of
     * the database column balance_checkpoint.balance
     * @return the value of balance_checkpoint.balance
     *
     * @mbg.generated
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the
     * database column balance_checkpoint.balance
     * @param balance the value for balance_checkpoint.balance
     *
     * @mbg.generated
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of
     * the database column balance_checkpoint.frozen
     * @return the value of balance_checkpoint.frozen
     *
     * @mbg.generated
     */
    public Long getFrozen() {
        return frozen;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the
     * database column balance_checkpoint.frozen
     * @param frozen the value for balance_checkpoint.frozen
     *
     * @mbg.generated
     */
    public void setFrozen(Long frozen) {
        this.frozen = frozen;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of
     * the database column balance_checkpoint.max_id
     * @return the value of balance_checkpoint.max_id
     *
     * @mbg.generated
     */
    public Long getMaxId() {
        return maxId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the
     * database column balance_checkpoint.max_id
     * @param maxId the value for balance_checkpoint.max_id
     *
     * @mbg.generated
     */
    public void setMaxId(Long maxId) {
        this.maxId = maxId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of
     * the database column balance_checkpoint.update_time
     * @return the value of balance_checkpoint.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the
     * database column balance_checkpoint.update_time
     * @param updateTime the value for balance_checkpoint.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", accountId=").append(accountId);
        sb.append(", balance=").append(balance);
        sb.append(", frozen=").append(frozen);
        sb.append(", maxId=").append(maxId);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BalanceCheckpoint other = (BalanceCheckpoint) that;
        return (this.getId() == null ? other.getId() == null
                : this.getId().equals(other.getId()))
                && (this.getUid() == null ? other.getUid() == null
                : this.getUid().equals(other.getUid()))
                && (this.getAccountId() == null ? other.getAccountId() == null
                : this.getAccountId().equals(other.getAccountId()))
                && (this.getBalance() == null ? other.getBalance() == null
                : this.getBalance().equals(other.getBalance()))
                && (this.getFrozen() == null ? other.getFrozen() == null
                : this.getFrozen().equals(other.getFrozen()))
                && (this.getMaxId() == null ? other.getMaxId() == null
                : this.getMaxId().equals(other.getMaxId()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null
                : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the
     * database table balance_checkpoint
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result
                + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getBalance() == null) ? 0 : getBalance().hashCode());
        result = prime * result + ((getFrozen() == null) ? 0 : getFrozen().hashCode());
        result = prime * result + ((getMaxId() == null) ? 0 : getMaxId().hashCode());
        result = prime * result
                + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator. This enum corresponds to the database
     * table balance_checkpoint
     *
     * @mbg.generated
     */
    public enum Column {

        id("id", "id", "BIGINT", false), uid("uid", "uid", "INTEGER", true), accountId(
                "account_id", "accountId", "VARCHAR",
                false), balance("balance", "balance", "BIGINT", false), frozen("frozen",
                "frozen", "BIGINT",
                false), maxId("max_id", "maxId", "BIGINT", false), updateTime(
                "update_time", "updateTime", "BIGINT", false);

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator. This field corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType,
               boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column)
                        .append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator. This method corresponds to the
         * database table balance_checkpoint
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }

    }

}
