package com.little.g.springcloud.pay.model;

import java.util.ArrayList;
import java.util.Arrays;

public class ChargeRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.tran_num
	 *
	 * @mbg.generated
	 */
	private String tranNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.uid
	 *
	 * @mbg.generated
	 */
	private Integer uid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.money
	 *
	 * @mbg.generated
	 */
	private Long money;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.status
	 *
	 * @mbg.generated
	 */
	private Byte status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.description
	 *
	 * @mbg.generated
	 */
	private String description;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.pay_type
	 *
	 * @mbg.generated
	 */
	private String payType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.preorder_no
	 *
	 * @mbg.generated
	 */
	private String preorderNo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.mch_id
	 *
	 * @mbg.generated
	 */
	private String mchId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.out_tran_num
	 *
	 * @mbg.generated
	 */
	private String outTranNum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.create_time
	 *
	 * @mbg.generated
	 */
	private Long createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column charge_record.update_time
	 *
	 * @mbg.generated
	 */
	private Long updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.tran_num
	 * @return the value of charge_record.tran_num
	 *
	 * @mbg.generated
	 */
	public String getTranNum() {
		return tranNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.tran_num
	 * @param tranNum the value for charge_record.tran_num
	 *
	 * @mbg.generated
	 */
	public void setTranNum(String tranNum) {
		this.tranNum = tranNum == null ? null : tranNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.uid
	 * @return the value of charge_record.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.uid
	 * @param uid the value for charge_record.uid
	 *
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.money
	 * @return the value of charge_record.money
	 *
	 * @mbg.generated
	 */
	public Long getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.money
	 * @param money the value for charge_record.money
	 *
	 * @mbg.generated
	 */
	public void setMoney(Long money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.status
	 * @return the value of charge_record.status
	 *
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.status
	 * @param status the value for charge_record.status
	 *
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.description
	 * @return the value of charge_record.description
	 *
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.description
	 * @param description the value for charge_record.description
	 *
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.pay_type
	 * @return the value of charge_record.pay_type
	 *
	 * @mbg.generated
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.pay_type
	 * @param payType the value for charge_record.pay_type
	 *
	 * @mbg.generated
	 */
	public void setPayType(String payType) {
		this.payType = payType == null ? null : payType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.preorder_no
	 * @return the value of charge_record.preorder_no
	 *
	 * @mbg.generated
	 */
	public String getPreorderNo() {
		return preorderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.preorder_no
	 * @param preorderNo the value for charge_record.preorder_no
	 *
	 * @mbg.generated
	 */
	public void setPreorderNo(String preorderNo) {
		this.preorderNo = preorderNo == null ? null : preorderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.mch_id
	 * @return the value of charge_record.mch_id
	 *
	 * @mbg.generated
	 */
	public String getMchId() {
		return mchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.mch_id
	 * @param mchId the value for charge_record.mch_id
	 *
	 * @mbg.generated
	 */
	public void setMchId(String mchId) {
		this.mchId = mchId == null ? null : mchId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.out_tran_num
	 * @return the value of charge_record.out_tran_num
	 *
	 * @mbg.generated
	 */
	public String getOutTranNum() {
		return outTranNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.out_tran_num
	 * @param outTranNum the value for charge_record.out_tran_num
	 *
	 * @mbg.generated
	 */
	public void setOutTranNum(String outTranNum) {
		this.outTranNum = outTranNum == null ? null : outTranNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.create_time
	 * @return the value of charge_record.create_time
	 *
	 * @mbg.generated
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.create_time
	 * @param createTime the value for charge_record.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column charge_record.update_time
	 * @return the value of charge_record.update_time
	 *
	 * @mbg.generated
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column charge_record.update_time
	 * @param updateTime the value for charge_record.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table charge_record
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", tranNum=").append(tranNum);
		sb.append(", uid=").append(uid);
		sb.append(", money=").append(money);
		sb.append(", status=").append(status);
		sb.append(", description=").append(description);
		sb.append(", payType=").append(payType);
		sb.append(", preorderNo=").append(preorderNo);
		sb.append(", mchId=").append(mchId);
		sb.append(", outTranNum=").append(outTranNum);
		sb.append(", createTime=").append(createTime);
		sb.append(", updateTime=").append(updateTime);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table charge_record
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ChargeRecord other = (ChargeRecord) that;
		return (this.getTranNum() == null ? other.getTranNum() == null
				: this.getTranNum().equals(other.getTranNum()))
				&& (this.getUid() == null ? other.getUid() == null
						: this.getUid().equals(other.getUid()))
				&& (this.getMoney() == null ? other.getMoney() == null
						: this.getMoney().equals(other.getMoney()))
				&& (this.getStatus() == null ? other.getStatus() == null
						: this.getStatus().equals(other.getStatus()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getPayType() == null ? other.getPayType() == null
						: this.getPayType().equals(other.getPayType()))
				&& (this.getPreorderNo() == null ? other.getPreorderNo() == null
						: this.getPreorderNo().equals(other.getPreorderNo()))
				&& (this.getMchId() == null ? other.getMchId() == null
						: this.getMchId().equals(other.getMchId()))
				&& (this.getOutTranNum() == null ? other.getOutTranNum() == null
						: this.getOutTranNum().equals(other.getOutTranNum()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table charge_record
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getTranNum() == null) ? 0 : getTranNum().hashCode());
		result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
		result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result
				+ ((getDescription() == null) ? 0 : getDescription().hashCode());
		result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
		result = prime * result
				+ ((getPreorderNo() == null) ? 0 : getPreorderNo().hashCode());
		result = prime * result + ((getMchId() == null) ? 0 : getMchId().hashCode());
		result = prime * result
				+ ((getOutTranNum() == null) ? 0 : getOutTranNum().hashCode());
		result = prime * result
				+ ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		result = prime * result
				+ ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		return result;
	}

	/**
	 * This enum was generated by MyBatis Generator. This enum corresponds to the database
	 * table charge_record
	 *
	 * @mbg.generated
	 */
	public enum Column {

		tranNum("tran_num", "tranNum", "VARCHAR", false), uid("uid", "uid", "INTEGER",
				true), money("money", "money", "BIGINT", false), status("status",
						"status", "TINYINT", true), description("description",
								"description", "VARCHAR", false), payType("pay_type",
										"payType", "VARCHAR",
										false), preorderNo("preorder_no", "preorderNo",
												"VARCHAR", false), mchId("mch_id",
														"mchId", "VARCHAR",
														false), outTranNum("out_tran_num",
																"outTranNum", "VARCHAR",
																false), createTime(
																		"create_time",
																		"createTime",
																		"BIGINT",
																		false), updateTime(
																				"update_time",
																				"updateTime",
																				"BIGINT",
																				false);

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		private static final String BEGINNING_DELIMITER = "`";

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		private static final String ENDING_DELIMITER = "`";

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		private final String column;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		private final boolean isColumnNameDelimited;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		private final String javaProperty;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		private final String jdbcType;

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public String value() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public String getValue() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public String getJavaProperty() {
			return this.javaProperty;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public String getJdbcType() {
			return this.jdbcType;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		Column(String column, String javaProperty, String jdbcType,
				boolean isColumnNameDelimited) {
			this.column = column;
			this.javaProperty = javaProperty;
			this.jdbcType = jdbcType;
			this.isColumnNameDelimited = isColumnNameDelimited;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public String desc() {
			return this.getEscapedColumnName() + " DESC";
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public String asc() {
			return this.getEscapedColumnName() + " ASC";
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public static Column[] excludes(Column... excludes) {
			ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
			if (excludes != null && excludes.length > 0) {
				columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
			}
			return columns.toArray(new Column[] {});
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public static Column[] all() {
			return Column.values();
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public String getEscapedColumnName() {
			if (this.isColumnNameDelimited) {
				return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column)
						.append(ENDING_DELIMITER).toString();
			}
			else {
				return this.column;
			}
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table charge_record
		 *
		 * @mbg.generated
		 */
		public String getAliasedEscapedColumnName() {
			return this.getEscapedColumnName();
		}

	}

}
