package com.little.g.springcloud.pay.model;

import java.util.ArrayList;
import java.util.Arrays;

public class UserAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.uid
	 *
	 * @mbg.generated
	 */
	private Integer uid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.money
	 *
	 * @mbg.generated
	 */
	private Long money;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.frozon_money
	 *
	 * @mbg.generated
	 */
	private Long frozonMoney;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.status
	 *
	 * @mbg.generated
	 */
	private Byte status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.update_time
	 *
	 * @mbg.generated
	 */
	private Long updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_account.create_time
	 *
	 * @mbg.generated
	 */
	private Long createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column user_account.uid
	 * @return the value of user_account.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column user_account.uid
	 * @param uid the value for user_account.uid
	 *
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column user_account.money
	 * @return the value of user_account.money
	 *
	 * @mbg.generated
	 */
	public Long getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column user_account.money
	 * @param money the value for user_account.money
	 *
	 * @mbg.generated
	 */
	public void setMoney(Long money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column user_account.frozon_money
	 * @return the value of user_account.frozon_money
	 *
	 * @mbg.generated
	 */
	public Long getFrozonMoney() {
		return frozonMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column user_account.frozon_money
	 * @param frozonMoney the value for user_account.frozon_money
	 *
	 * @mbg.generated
	 */
	public void setFrozonMoney(Long frozonMoney) {
		this.frozonMoney = frozonMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column user_account.status
	 * @return the value of user_account.status
	 *
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column user_account.status
	 * @param status the value for user_account.status
	 *
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column user_account.update_time
	 * @return the value of user_account.update_time
	 *
	 * @mbg.generated
	 */
	public Long getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column user_account.update_time
	 * @param updateTime the value for user_account.update_time
	 *
	 * @mbg.generated
	 */
	public void setUpdateTime(Long updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of
	 * the database column user_account.create_time
	 * @return the value of user_account.create_time
	 *
	 * @mbg.generated
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the
	 * database column user_account.create_time
	 * @param createTime the value for user_account.create_time
	 *
	 * @mbg.generated
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", uid=").append(uid);
		sb.append(", money=").append(money);
		sb.append(", frozonMoney=").append(frozonMoney);
		sb.append(", status=").append(status);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", createTime=").append(createTime);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UserAccount other = (UserAccount) that;
		return (this.getUid() == null ? other.getUid() == null
				: this.getUid().equals(other.getUid()))
				&& (this.getMoney() == null ? other.getMoney() == null
						: this.getMoney().equals(other.getMoney()))
				&& (this.getFrozonMoney() == null ? other.getFrozonMoney() == null
						: this.getFrozonMoney().equals(other.getFrozonMoney()))
				&& (this.getStatus() == null ? other.getStatus() == null
						: this.getStatus().equals(other.getStatus()))
				&& (this.getUpdateTime() == null ? other.getUpdateTime() == null
						: this.getUpdateTime().equals(other.getUpdateTime()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table user_account
	 *
	 * @mbg.generated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
		result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
		result = prime * result
				+ ((getFrozonMoney() == null) ? 0 : getFrozonMoney().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result
				+ ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
		result = prime * result
				+ ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		return result;
	}

	/**
	 * This enum was generated by MyBatis Generator. This enum corresponds to the database
	 * table user_account
	 *
	 * @mbg.generated
	 */
	public enum Column {

		uid("uid", "uid", "INTEGER", true), money("money", "money", "BIGINT",
				false), frozonMoney("frozon_money", "frozonMoney", "BIGINT",
						false), status("status", "status", "TINYINT", true), updateTime(
								"update_time", "updateTime", "BIGINT", false), createTime(
										"create_time", "createTime", "BIGINT", false);

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		private static final String BEGINNING_DELIMITER = "`";

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		private static final String ENDING_DELIMITER = "`";

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		private final String column;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		private final boolean isColumnNameDelimited;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		private final String javaProperty;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		private final String jdbcType;

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public String value() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public String getValue() {
			return this.column;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public String getJavaProperty() {
			return this.javaProperty;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public String getJdbcType() {
			return this.jdbcType;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		Column(String column, String javaProperty, String jdbcType,
				boolean isColumnNameDelimited) {
			this.column = column;
			this.javaProperty = javaProperty;
			this.jdbcType = jdbcType;
			this.isColumnNameDelimited = isColumnNameDelimited;
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public String desc() {
			return this.getEscapedColumnName() + " DESC";
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public String asc() {
			return this.getEscapedColumnName() + " ASC";
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public static Column[] excludes(Column... excludes) {
			ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
			if (excludes != null && excludes.length > 0) {
				columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
			}
			return columns.toArray(new Column[] {});
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public static Column[] all() {
			return Column.values();
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public String getEscapedColumnName() {
			if (this.isColumnNameDelimited) {
				return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column)
						.append(ENDING_DELIMITER).toString();
			}
			else {
				return this.column;
			}
		}

		/**
		 * This method was generated by MyBatis Generator. This method corresponds to the
		 * database table user_account
		 *
		 * @mbg.generated
		 */
		public String getAliasedEscapedColumnName() {
			return this.getEscapedColumnName();
		}

	}

}
