package com.little.g.springcloud.thirdpay.mapper;

import com.little.g.springcloud.thirdpay.model.PayChannel;
import com.little.g.springcloud.thirdpay.model.PayChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayChannelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	long countByExample(PayChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PayChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	int insert(PayChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	int insertSelective(PayChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	PayChannel selectOneByExample(PayChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	PayChannel selectOneByExampleSelective(@Param("example") PayChannelExample example,
			@Param("selective") PayChannel.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	List<PayChannel> selectByExampleSelective(@Param("example") PayChannelExample example,
			@Param("selective") PayChannel.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	List<PayChannel> selectByExample(PayChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	PayChannel selectByPrimaryKeySelective(@Param("id") Integer id,
			@Param("selective") PayChannel.Column... selective);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	PayChannel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") PayChannel record,
			@Param("example") PayChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") PayChannel record,
			@Param("example") PayChannelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PayChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table pay_channel
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PayChannel record);

}